import { supabase } from './supabaseClient'

// Default categories
const DEFAULT_CATEGORIES = [
  { value: 'memories', label: 'Amintiri', emoji: '💭' },
  { value: 'milestones', label: 'Etape importante', emoji: '🎯' },
  { value: 'everyday', label: 'Zilnic', emoji: '☀️' },
  { value: 'special', label: 'Special', emoji: '✨' },
  { value: 'family', label: 'Familie', emoji: '👨‍👩‍👧‍👦' },
  { value: 'play', label: 'Joacă', emoji: '🎮' },
  { value: 'learning', label: 'Învățare', emoji: '📚' }
]

// Auto-create table and initialize categories for a family
export async function ensureFamilyCategories(familyId) {
  try {
    // First, try to check if the table exists by running a simple query
    const { data: testData, error: testError } = await supabase
      .from('family_categories')
      .select('id')
      .eq('family_id', familyId)
      .limit(1)

    // If table doesn't exist, try to create it
    if (testError && (testError.message.includes('does not exist') || testError.code === '42P01')) {
      console.log('Creating family_categories table...')
      
      // Try to create table using raw SQL
      const createTableSQL = `
        CREATE TABLE IF NOT EXISTS family_categories (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          family_id UUID NOT NULL,
          category_value VARCHAR(100) NOT NULL,
          category_label VARCHAR(200) NOT NULL,
          category_emoji VARCHAR(10) DEFAULT '📝',
          created_at TIMESTAMPTZ DEFAULT NOW(),
          updated_at TIMESTAMPTZ DEFAULT NOW(),
          UNIQUE(family_id, category_value)
        );
        
        CREATE INDEX IF NOT EXISTS idx_family_categories_family_id ON family_categories(family_id);
        CREATE INDEX IF NOT EXISTS idx_family_categories_value ON family_categories(family_id, category_value);
      `
      
      // This might not work due to RLS, but we'll try
      try {
        await supabase.rpc('exec_sql', { sql: createTableSQL })
      } catch (sqlError) {
        console.log('Could not create table automatically:', sqlError.message)
        // Table creation failed, return defaults
        return DEFAULT_CATEGORIES
      }
    }

    // Now check if this family has categories
    const { data: existingCategories, error: fetchError } = await supabase
      .from('family_categories')
      .select('*')
      .eq('family_id', familyId)

    if (fetchError) {
      console.error('Error fetching family categories:', fetchError)
      // If table doesn't exist, return defaults for now
      return DEFAULT_CATEGORIES
    }

    // If family has no categories, insert defaults
    if (!existingCategories || existingCategories.length === 0) {
      const categoriesToInsert = DEFAULT_CATEGORIES.map(cat => ({
        family_id: familyId,
        category_value: cat.value,
        category_label: cat.label,
        category_emoji: cat.emoji
      }))

      const { error: insertError } = await supabase
        .from('family_categories')
        .insert(categoriesToInsert)

      if (insertError) {
        console.error('Error inserting default categories:', insertError)
        return DEFAULT_CATEGORIES
      }

      return DEFAULT_CATEGORIES
    }

    // Return existing categories
    return existingCategories.map(cat => ({
      value: cat.category_value,
      label: cat.category_label,
      emoji: cat.category_emoji
    }))

  } catch (error) {
    console.error('Error in ensureFamilyCategories:', error)
    return DEFAULT_CATEGORIES
  }
}