import { useState } from 'react'
import { supabase } from '../lib/supabaseClient'

export default function AdminSetup() {
  const [status, setStatus] = useState('')
  const [isLoading, setIsLoading] = useState(false)

  const createTable = async () => {
    setIsLoading(true)
    setStatus('Creating family_categories table...')

    try {
      // First, let's try to insert test data to see if table exists
      const { data: families, error: familiesError } = await supabase
        .from('families')
        .select('id')
        .limit(1)

      if (familiesError || !families || families.length === 0) {
        setStatus('❌ Error: No families found in database')
        setIsLoading(false)
        return
      }

      const testFamilyId = families[0].id

      // Test if table exists by trying to insert
      const { error: testError } = await supabase
        .from('family_categories')
        .insert([{
          family_id: testFamilyId,
          category_value: 'test-table-exists',
          category_label: 'Test',
          category_emoji: '🔧'
        }])

      if (testError) {
        if (testError.message.includes('does not exist') || 
            testError.message.includes('schema cache') ||
            testError.code === '42P01') {
          setStatus(`❌ Table does not exist. Error: ${testError.message}`)
        } else {
          setStatus(`❌ Database error: ${testError.message}`)
        }
        setIsLoading(false)
        return
      }

      // If we got here, table exists. Clean up test record
      await supabase
        .from('family_categories')
        .delete()
        .eq('category_value', 'test-table-exists')

      setStatus('✅ Table already exists! Setting up default categories...')

      // Set up default categories for all families
      const setupResult = await fetch('/api/admin/setup-categories', {
        method: 'POST'
      })

      const setupData = await setupResult.json()

      if (setupResult.ok) {
        setStatus(`✅ Success! Categories setup completed for ${setupData.familiesSetup}/${setupData.totalFamilies} families`)
      } else {
        setStatus(`❌ Setup failed: ${setupData.error}`)
      }

    } catch (error) {
      setStatus(`❌ Unexpected error: ${error.message}`)
    }

    setIsLoading(false)
  }

  return (
    <div style={{ 
      maxWidth: '800px', 
      margin: '0 auto', 
      padding: '40px 20px',
      fontFamily: 'Arial, sans-serif'
    }}>
      <h1>Admin Setup - Family Categories</h1>
      
      <div style={{ 
        marginBottom: '20px',
        padding: '20px',
        backgroundColor: '#f0f9ff',
        border: '1px solid #0ea5e9',
        borderRadius: '8px'
      }}>
        <h2>📋 Instructions</h2>
        <p>This page will help you set up the family_categories table for the category system.</p>
        <ol>
          <li><strong>First:</strong> You need to create the table manually in Supabase Dashboard</li>
          <li><strong>Then:</strong> Click "Setup Categories" below to populate default categories</li>
        </ol>
      </div>

      <div style={{ 
        marginBottom: '20px',
        padding: '20px',
        backgroundColor: '#fefce8',
        border: '1px solid #eab308',
        borderRadius: '8px'
      }}>
        <h3>🔧 Manual Table Creation Required</h3>
        <p>Go to your <strong>Supabase Dashboard → SQL Editor</strong> and run this SQL:</p>
        <pre style={{ 
          backgroundColor: '#1f2937',
          color: '#f9fafb',
          padding: '16px',
          borderRadius: '8px',
          overflow: 'auto',
          fontSize: '14px'
        }}>
{`CREATE TABLE family_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id UUID NOT NULL REFERENCES families(id) ON DELETE CASCADE,
  category_value VARCHAR(100) NOT NULL,
  category_label VARCHAR(200) NOT NULL,
  category_emoji VARCHAR(10) DEFAULT '📝',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(family_id, category_value)
);

CREATE INDEX idx_family_categories_family_id ON family_categories(family_id);
ALTER TABLE family_categories ENABLE ROW LEVEL SECURITY;`}
        </pre>
      </div>

      <button 
        onClick={createTable}
        disabled={isLoading}
        style={{
          padding: '12px 24px',
          fontSize: '16px',
          backgroundColor: isLoading ? '#9ca3af' : '#3b82f6',
          color: 'white',
          border: 'none',
          borderRadius: '8px',
          cursor: isLoading ? 'not-allowed' : 'pointer',
          marginBottom: '20px'
        }}
      >
        {isLoading ? 'Setting up...' : 'Setup Categories'}
      </button>

      {status && (
        <div style={{ 
          padding: '16px',
          backgroundColor: status.startsWith('✅') ? '#f0fdf4' : '#fef2f2',
          border: `1px solid ${status.startsWith('✅') ? '#22c55e' : '#ef4444'}`,
          borderRadius: '8px',
          marginTop: '20px',
          whiteSpace: 'pre-wrap'
        }}>
          <strong>Status:</strong> {status}
        </div>
      )}
    </div>
  )
}