import { supabase } from '../../../lib/supabaseClient'
import { requireEditor } from '../../../lib/authMiddleware'

async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  const familyId = req.auth.familyId

  try {
    console.log('Auto-migrating categories for family:', familyId)

    // Default categories
    const DEFAULT_CATEGORIES = [
      { value: 'memories', label: 'Amintiri', emoji: '💭' },
      { value: 'milestones', label: 'Etape importante', emoji: '🎯' },
      { value: 'everyday', label: 'Zilnic', emoji: '☀️' },
      { value: 'special', label: 'Special', emoji: '✨' },
      { value: 'family', label: 'Familie', emoji: '👨‍👩‍👧‍👦' },
      { value: 'play', label: 'Joacă', emoji: '🎮' },
      { value: 'learning', label: 'Învățare', emoji: '📚' }
    ]

    // Create the table first using SQL
    const createTableSQL = `
      CREATE TABLE IF NOT EXISTS family_categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        family_id UUID NOT NULL,
        category_value VARCHAR(100) NOT NULL,
        category_label VARCHAR(200) NOT NULL,
        category_emoji VARCHAR(10) DEFAULT '📝',
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW(),
        UNIQUE(family_id, category_value)
      );
      
      CREATE INDEX IF NOT EXISTS idx_family_categories_family_id ON family_categories(family_id);
      CREATE INDEX IF NOT EXISTS idx_family_categories_value ON family_categories(family_id, category_value);
    `

    // Try to create table - this might fail due to permissions, that's OK
    try {
      await supabase.rpc('exec_sql', { sql: createTableSQL })
      console.log('Table created successfully')
    } catch (sqlError) {
      console.log('Table creation skipped (might already exist):', sqlError.message)
    }

    // Now try to insert categories for this family
    const categoriesToInsert = DEFAULT_CATEGORIES.map(cat => ({
      family_id: familyId,
      category_value: cat.value,
      category_label: cat.label,
      category_emoji: cat.emoji
    }))

    const { error: insertError } = await supabase
      .from('family_categories')
      .insert(categoriesToInsert)

    if (insertError && !insertError.message.includes('duplicate key')) {
      console.error('Insert error:', insertError)
      // If we can't insert, return defaults anyway
      return res.status(200).json({
        success: true,
        categories: DEFAULT_CATEGORIES,
        message: 'Using default categories (database migration pending)'
      })
    }

    res.status(200).json({
      success: true,
      categories: DEFAULT_CATEGORIES,
      message: 'Categories initialized successfully'
    })
  } catch (error) {
    console.error('Auto-migration error:', error)
    
    // Return defaults as fallback
    res.status(200).json({
      success: true,
      categories: [
        { value: 'memories', label: 'Amintiri', emoji: '💭' },
        { value: 'milestones', label: 'Etape importante', emoji: '🎯' },
        { value: 'everyday', label: 'Zilnic', emoji: '☀️' },
        { value: 'special', label: 'Special', emoji: '✨' },
        { value: 'family', label: 'Familie', emoji: '👨‍👩‍👧‍👦' },
        { value: 'play', label: 'Joacă', emoji: '🎮' },
        { value: 'learning', label: 'Învățare', emoji: '📚' }
      ],
      message: 'Using default categories (auto-migration failed)'
    })
  }
}

export default requireEditor(handler)