-- Create the family_categories table
CREATE TABLE family_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id UUID NOT NULL REFERENCES families(id) ON DELETE CASCADE,
  category_value VARCHAR(100) NOT NULL,
  category_label VARCHAR(200) NOT NULL,
  category_emoji VARCHAR(10) DEFAULT '📝',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(family_id, category_value)
);

-- Create index for better performance
CREATE INDEX idx_family_categories_family_id ON family_categories(family_id);

-- Enable Row Level Security
ALTER TABLE family_categories ENABLE ROW LEVEL SECURITY;

-- Add RLS policies
CREATE POLICY "Users can view categories for their family" ON family_categories
  FOR SELECT USING (
    family_id IN (
      SELECT family_id FROM user_family_access 
      WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert categories for their family" ON family_categories
  FOR INSERT WITH CHECK (
    family_id IN (
      SELECT family_id FROM user_family_access 
      WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update categories for their family" ON family_categories
  FOR UPDATE USING (
    family_id IN (
      SELECT family_id FROM user_family_access 
      WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can delete categories for their family" ON family_categories
  FOR DELETE USING (
    family_id IN (
      SELECT family_id FROM user_family_access 
      WHERE user_id = auth.uid()
    )
  );