-- Create family_categories table for per-family custom categories
-- This table stores custom categories that each family can define

CREATE TABLE IF NOT EXISTS family_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id UUID NOT NULL REFERENCES families(id) ON DELETE CASCADE,
  category_value VARCHAR(100) NOT NULL,
  category_label VARCHAR(200) NOT NULL,
  category_emoji VARCHAR(10) DEFAULT '📝',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(family_id, category_value)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_family_categories_family_id ON family_categories(family_id);
CREATE INDEX IF NOT EXISTS idx_family_categories_value ON family_categories(family_id, category_value);

-- Set up Row Level Security (RLS)
ALTER TABLE family_categories ENABLE ROW LEVEL SECURITY;

-- RLS policy: families can only access their own categories
CREATE POLICY "Families can view their own categories" ON family_categories
  FOR SELECT USING (
    family_id IN (
      SELECT id FROM families WHERE id = family_id
    )
  );

CREATE POLICY "Families can insert their own categories" ON family_categories
  FOR INSERT WITH CHECK (
    family_id IN (
      SELECT id FROM families WHERE id = family_id
    )
  );

CREATE POLICY "Families can update their own categories" ON family_categories
  FOR UPDATE USING (
    family_id IN (
      SELECT id FROM families WHERE id = family_id
    )
  );

CREATE POLICY "Families can delete their own categories" ON family_categories
  FOR DELETE USING (
    family_id IN (
      SELECT id FROM families WHERE id = family_id
    )
  );

-- Grant necessary permissions
GRANT ALL ON family_categories TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE family_categories_id_seq TO authenticated;

-- Insert default categories for existing families (optional)
-- Note: This will only insert if there are no existing categories for each family
INSERT INTO family_categories (family_id, category_value, category_label, category_emoji)
SELECT 
  f.id as family_id,
  unnest(ARRAY['memories', 'milestones', 'everyday', 'special', 'family', 'play', 'learning']) as category_value,
  unnest(ARRAY['Amintiri', 'Etape importante', 'Zilnic', 'Special', 'Familie', 'Joacă', 'Învățare']) as category_label,
  unnest(ARRAY['💭', '🎯', '☀️', '✨', '👨‍👩‍👧‍👦', '🎮', '📚']) as category_emoji
FROM families f
WHERE NOT EXISTS (
  SELECT 1 FROM family_categories fc WHERE fc.family_id = f.id
)
ON CONFLICT (family_id, category_value) DO NOTHING;